### ISSUE TITLE
[enhancement]: Support for renaming variables (F2)

### ISSUE THREAD

**Issue by StaticNoiseLog** [FFriZ/Pine-Script-v5-VS-Code#2]
**Description:**
It would be very helpful if we could rename Pine Script variables in a controlled manner.
The only way to do something similar currently is editor.action.changeAll, which is just a global string replacement without any respect for the programming language.
Enhancing this extension so that we can use F2 for properly renaming variables (and functions) would be awesome.
This is the key and command I am referring to:
```
{
  "key": "f2",
  "command": "editor.action.rename",
  "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly"
}
```
**Steps To Reproduce:**
Select a variable
Press F2

**Expected Behavior:**
A small box should pop up that lets us rename the selected variable.

**Actual Behavior:**
No action

**VS Code Version:**
1.85.2

**Operating System:**
Microsoft Windows [Version 10.0.19045.3930]

(Thanks for starting this project, it already brings a lot of helpful features!)

**Comment by FFriZ** [comment]
You should be able to update your extension now and F2 should work  (for the time being if the variable being changed is the same as a function argument the function argument may be changed as well)
